# NumPy Basics Exercises

A short practice notebook built from my original `04-Numpy Exercises.ipynb` while reviewing core NumPy array operations.

## Goal

I wanted a compact notebook that checks the basics: creating arrays, reshaping data, sampling random values, slicing matrices, and applying simple aggregations.

In [1]:
import numpy as np

np.random.seed(42)

## Array Creation

Create an array of 10 zeros.

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Create an array of 10 ones.

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Create an array of 10 fives.

In [4]:
np.full(10, 5)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

Create an array of the integers from 10 to 50.

In [5]:
np.arange(10, 51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

Create an array of all even integers from 10 to 50.

In [6]:
np.arange(10, 51, 2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

Create a `3 x 3` matrix with values ranging from 0 to 8.

In [7]:
np.arange(9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Create a `3 x 3` identity matrix.

In [8]:
np.eye(3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

## Random Values and Reshaping

Generate one random number between 0 and 1.

In [9]:
np.random.rand()

0.3745401188473625

Generate 25 random numbers from a standard normal distribution.

In [10]:
np.random.randn(25)

array([-1.11188012,  0.31890218,  0.27904129,  1.01051528, -0.58087813,
       -0.52516981, -0.57138017, -0.92408284, -2.61254901,  0.95036968,
        0.81644508, -1.523876  , -0.42804606, -0.74240684, -0.7033438 ,
       -2.13962066, -0.62947496,  0.59772047,  2.55948803,  0.39423302,
        0.12221917, -0.51543566, -0.60025385,  0.94743982,  0.291034  ])

Build a `10 x 10` matrix with values from `0.01` to `1.00`.

In [11]:
(np.arange(1, 101) / 100).reshape(10, 10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

Create 20 linearly spaced points between 0 and 1.

In [12]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Indexing and Selection

Use the matrix below for the next few selections.

In [13]:
mat = np.arange(1, 26).reshape(5, 5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

Select the block:

```python
array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])
```

In [14]:
mat[2:, 1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

Get the value `20`.

In [15]:
mat[3, 4]

np.int64(20)

Select the column vector:

```python
array([[ 2],
       [ 7],
       [12]])
```

In [16]:
mat[:3, 1:2]

array([[ 2],
       [ 7],
       [12]])

Get the final row of the matrix.

In [17]:
mat[4, :]

array([21, 22, 23, 24, 25])

Get the bottom two rows.

In [18]:
mat[3:, :]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

## Aggregations

Get the sum of all values in `mat`.

In [19]:
mat.sum()

np.int64(325)

Get the standard deviation of the values in `mat`.

In [20]:
mat.std()

np.float64(7.211102550927978)

Get the sum of each column in `mat`.

In [21]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

## What I Learned

NumPy gets much easier once slicing rules feel natural. Most of these tasks are small, but they cover patterns that show up again in preprocessing, feature engineering, and model input preparation.